language: node_js
node_js:
- 4.1.1
- node
before_install:
	-npm install -g grunt-cli
	-cd Client
	-bower install
install: npm install
before_script: grunt build --ytKey=$YT_API_KEY
env:
  matrix:
    secure: RgXnD5SE0IUL7/NcWKtxMwCgipwlU1W0sw0VagTwlJ9Es6Pno5ia0Xhct5t0BS/5BwSjxQQHbD1pL+4a8pGB22OkVzXwyaesdwK+ytSEeO8oDEA5VFVl5zpOrpCpDefj5dKSOpjv5EG5lzWmmwuVGdSRBHqbWZgZ2w0nADiVlZJUiIFYmTwrYXDWatK/0OZvxW3UM5RUiRvCGLaE4kV//KcIwzBwAOpMtygPIpVmokRMcHp0EK4Ij/goyy9mnJb5eDXHga/7Oep3AP0JjpCjz2ISiAq3Fx8urY9Eab0Gu+qobCt0yNkwb8BpnqKdhpglWnwlnXhZjCisGQCI4+Hpjnhpeg+oHEBrOPwK3sTB5ouwjgDk2G+yvYYYRDMoHVC0g7WIbxbR9f361WeAE+P4JIXDRPiIsIlVIHwEpSM4k8xlvIyZbdmsuXrk4h4cJ6G49C/xawKlciyPlmAoG9/zp4qDI0vk2lMxDpR8D9gjWXaFJOHcQWNp2/xna7Yb8QJAPyPEIe7/lo+m9A38c7law9XSIZsK4Kxf7xmZYUCWdyoTZwwWzFDJGkdt3J2GKJczpEP/5mad+gkJGsDdzD0SKeETqEPszQE8y2Vk9bpSWTnDMhqQVfShjNRv4R6C0a5HtOHfvfd2OUE74Iom3Q1U8EjHGYblLFqEP1rkuyYPr/A=
